# For the nav bar
urls:
    - text: Posts
      url: /posts
    - text: Research
      url: /research
    - text: Talks
      url: /talks
    # - text: Projects
    #   url: https://github.com/ariG23498?tab=repositories
    # - text: Resume
    #   url: /assets/Aritra_Resume.pdf

title: Portfolio
email: aritra.roy.g@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ariG23498.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ariG23498
github_username:  ariG23498

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-sitemap


# For highlighting code
highlighter: rouge
markdown: kramdown
defaults:
  - scope:
      path: ""
      type: posts
    values:
      mathjax: true
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CLAUDE.md
  - README.md
  - LICENSE
  - dev.sh
  - SECURITY.md
